### ISSUE TITLE
Solutions for week0

### ISSUE THREAD

**Issue by RadoRado** [HackBulgaria/Core-Ruby-1#30]
Hello there @gsamokovarov ^_^

I started taking this course and solving problems for week0.

Is there any solutions from you available, so I can compare my solutions & get better ideas? (I am still writing Python-like Ruby :D)

https://github.com/HackBulgaria/Core-Ruby-1/tree/master/week0/1-standard-types

**Comment by gsamokovarov** [comment]
Hey, glad to hear you're starting with them Rubies :smile_cat:

Here you go: http://ruby.hackbulgaria.com/lecture-03/#/39

**Comment by RadoRado** [comment]
That is great, thanks!
